---
title: ""
author: "Vera Singh RN, MPH"
output: 
  html_document:
    theme: yeti
    css: styles.css
---

# Welcome to VeracityPV Consulting

_Pharmacovigilance Guaranteed!_

Providing interim pharmacovigilance services to your organization: Your Safety/PV Department as you grow.

---

## <a id="about"></a>About
Vera has over 20 years experience in pharmacovigilance and drug safety. She has worked in large multinational companies and start-up biotech companies with “IND to NDA” experience across most therapeutic areas and modalities. Her expertise ranges from pharmacovigilance operations to signal detection. She has created systems and processes to ensure inspection readiness and regulatory compliance. Her motto is: _“ensuring drug safety is not a choice but a philosophy“_.

---

## <a id="who-we-support"></a>Who We Support

- Start-up companies that require PV support to be compliant 
- Your Safety/PV Department as you grow
- Clinical stage/premarketing stage companies
- Supporting with PV needs and establishing systems, processes for inspection readiness
- Established companies with marketed products: Providing ad-hoc resources and support

---

## <a id="what-we-do"></a>What We Do

1. **Safety Surveillance**
2. **Operations**
    - SOPs and Inspection Readiness
    - Governance, Communication, Reporting, Review
    - Regulatory reporting of ICSR
    - Evaluating RFI/RFQ
    - Budget, onboarding, governance, KPI, QA/QC
    - ARGUS, ARSG, Medidata Rave EDC (Electronic Data Capture); Data reconciliation, MedDRA, WHODrug
    - Signal detection
    - Creation, review of Critical Safety Documents
    - Aggregate report (PSUR, DSUR, SUSAR) ICSR
    - Create governance structure to review safety signals
    - Vendor Management
    - Systems & Databases

---

## How We Do It?

1. Contact us for an initial consultation to understand your needs.
2. Provide recommendations (build, insource, outsource).
3. Establish systems, process and teams.

---

## <a id="contact-us"></a>Contact Us

**Veracity PV Consulting**  
5776 Lindero Canyon Road, Suite D-126  
Westlake Village, CA 91362  
Email: [veracitypv@gmail.com](mailto:veracitypv@gmail.com)  
Website: [www.veracitypv.com](http://www.veracitypv.com)  
Phone: [+1-805-338-9001](tel:+18053389001)

---

## Privacy Notice

Last updated: 01 September 2023

<span id="privacy-hover">Click here to read our Privacy Notice</span>

<div id="privacy-content">
    
**Privacy Notice**  
Last updated: 01 September 2023

Thank you for visiting VeracityPV.com ("we," "us," "our"). This Privacy Notice explains how we collect, use, disclose, and safeguard your information when you visit our website www.veracitypv.com (the "Website"). Please read this Privacy Notice carefully...

(Include the rest of the Privacy Notice here)

</div>

